language: node_js
node_js:
- '12'
addons:
  sonarcloud:
    organization: "msanchezv"
branches:
  only:
  - develop
  - "/^release-[0-999].[0-999]$/"
  - master
notifications:
  email:
    recipients:
    - masanchezve@gmail.com
    - sonia.bejar017@gmail.com
script:
  - sonar-scanner
deploy:
  provider: heroku
  api_key: $HEROKU
  on:
    branch: master
